name: Configure GitHub Container Registry
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: test-app-aiomi-admin-panel
  USERNAME: AnuarKazah
  TOKEN: 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
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}
          
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Docker image checksum
        run: echo ${{ env.IMAGE_NAME }} digest is ${{ steps.docker_info.outputs.digest }} 

      - name: Logout of GitHub Container Registry
        uses: docker/logout-action@v1
